Repository VivekChatterjee/movie-reviewer, pull requests merged in 2023-10, with the labels that each got.

#4 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 Enhanced the website
  index.jsx
  style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#20 Update style.css
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#21 Background Animations
  background.js
  index.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
